#!/bin/sh
#YANG ZHANG
#CSE 374 HW2
#PROBLEM 3
#Tue Jan 21 14:46:28 PST 2014

if [ $# -lt 2 ] # "$#" is the number of arguments
then 
	echo "Error: less than two arguments" >&2
	exit 1
else
	if [ -e "$1" ]   # -e is FILE TEST OPERATOR for file exists
	then
		echo "Error: first file exists" >&2
		exit 1
	else
		echo >> "$1" 
		FILE_NAME="$1"
		shift
	fi
	for arg in "$@"
	do
		if [ -d "$arg" ]
		then
			echo "Error: $arg is a dirctory" >>"$FILE_NAME"
		elif [ ! -e "$arg" ]
		then	
			echo "Error: $arg doesn't exist" >>"$FILE_NAME"
		else
			echo $(cat "$arg")  
		fi
	done
fi
echo $(tail -n +2 "$FILE_NAME") >"$FILE_NAME" #remove the first blank line
		
